POST http://localhost:3000/users
Content-Type: application/json
{
  "firstName": "senha desse e",
  "lastName": "@password1234",
  "email": "exemplo2@example.com",
  "password": "@password1234"
}

POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjY5LCJlbWFpbCI6ImV4ZW1wbG8yQGV4YW1wbGUuY29tIiwiaWF0IjoxNzQ3NTM1NzM3LCJleHAiOjE3NDc1MzkzMzcsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.5Fza5lL60ojbV71ROmCLSx5OaIhTIMeCqSVb66YvzGI
{
  "createManyUsers": 
  [
    {
  "firstName": "John Doe",
  "lastName": "John Doe",
  "email":"jonih@gmail.com",
  "password": "@password123",
  "auth":"teste"
    },
    {
  "firstName": "Mark Doe",
  "lastName": "John Doe",
  "email":"markinho@gmail.com",
  "password": "@password123",
  "auth":"teste"
    },
    {
  "firstName": "Jesse Doe",
  "lastName": "Jesse Doe",
  "email":"jesse@gmail.com",
  "password": "@password123",
  "auth":"teste"
    }
  ]
}